import { Pokemon } from "./pokemon";
import { PokemonType } from "./pokemons interfaces/pokemonType";

export type PokemonList = Pokemon[];

const fireType:PokemonType = { name: "Feu", cssColor: "red lighten-1" };
const waterType:PokemonType = { name: "Eau", cssColor: "blue lighten-1" };
const plantType:PokemonType = { name: "Plante", cssColor: "green lighten-1" };
const insectType:PokemonType = { name: "Insecte", cssColor: "brown lighten-1" };
const normalType:PokemonType = { name: "Normal", cssColor: "grey lighten-3" };
const FlyType:PokemonType = { name: "Vol", cssColor: "blue lighten-3" };
const PoisonType:PokemonType = { name: "Poison", cssColor: "deep-purple accent-1" };
const FeeType:PokemonType = { name: "Fée", cssColor: "pink lighten-4" };
const electrikType:PokemonType = { name: "Electrik", cssColor: "'lime accent-1" };
const psyType:PokemonType = { name: "Psy", cssColor: "deep-purple darken-2" };
const combatType:PokemonType = { name: "Combat", cssColor: "deep-orange" };

export const pokemonTypes: PokemonType[] = [
  fireType,
  waterType,
  plantType,
  insectType,
  normalType,
  FlyType,
  PoisonType,
  FeeType,
  electrikType,
  psyType,
  combatType,];

export const POKEMONS: PokemonList = [
  {
    id: 1,
    name: "Bulbizarre",
    hp: 25,
    cp: 5,
    damage: 6,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png",
    types: [plantType, PoisonType],
    created: new Date(),
  },
  {
    id: 2,
    name: "Salamèche",
    hp: 28,
    cp: 6,
    damage: 6,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/004.png",
    types: [fireType],
    created: new Date(),
  },
  {
    id: 3,
    name: "Carapuce",
    hp: 21,
    cp: 4,
    damage: 6,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/007.png",
    types: [waterType],
    created: new Date(),
  },
  {
    id: 4,
    name: "Aspicot",
    hp: 16,
    cp: 2,
    damage: 6,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/013.png",
    types: [insectType, PoisonType],
    created: new Date(),
  },
  {
    id: 5,
    name: "Roucool",
    hp: 30,
    cp: 7,
    damage: 6,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/016.png",
    types: [normalType, FlyType],
    created: new Date(),
  },
  {
    id: 6,
    name: "Rattata",
    hp: 18,
    cp: 6,
    damage: 6,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/019.png",
    types: [normalType],
    created: new Date(),
  },
  {
    id: 7,
    name: "Piafabec",
    hp: 14,
    cp: 5,
    damage: 6,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/021.png",
    types: [normalType, FlyType],
    created: new Date(),
  },
  {
    id: 8,
    name: "Abo",
    hp: 16,
    cp: 4,
    damage: 6,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/023.png",
    types: [PoisonType],
    created: new Date(),
  },
  {
    id: 9,
    name: "Pikachu",
    hp: 21,
    cp: 7,
    damage: 6,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/025.png",
    types: [electrikType],
    created: new Date(),
  },
  {
    id: 10,
    name: "Sabelette",
    hp: 19,
    cp: 3,
    damage: 6,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/027.png",
    types: [normalType],
    created: new Date(),
  },
  {
    id: 11,
    name: "Mélofée",
    hp: 25,
    cp: 5,
    damage: 6,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/035.png",
    types: [FeeType],
    created: new Date(),
  },
  {
    id: 12,
    name: "Groupix",
    hp: 17,
    cp: 8,
    damage: 6,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/037.png",
    types: [fireType],
    created: new Date(),
  },
  // Popular Pokémon additions
  {
    id: 13,
    name: "Dracaufeu",
    hp: 30,
    cp: 10,
    damage: 8,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/006.png",
    types: [fireType, FlyType],
    created: new Date(),
  },
  {
    id: 14,
    name: "Tortank",
    hp: 30,
    cp: 10,
    damage: 8,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/009.png",
    types: [waterType],
    created: new Date(),
  },
  {
    id: 15,
    name: "Florizarre",
    hp: 30,
    cp: 10,
    damage: 8,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/003.png",
    types: [plantType, PoisonType],
    created: new Date(),
  },
  {
    id: 16,
    name: "Rondoudou",
    hp: 22,
    cp: 4,
    damage: 5,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/039.png",
    types: [normalType, FeeType],
    created: new Date(),
  },
  {
    id: 17,
    name: "Evoli",
    hp: 20,
    cp: 6,
    damage: 6,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/133.png",
    types: [normalType],
    created: new Date(),
  },
  {
    id: 18,
    name: "Aquali",
    hp: 28,
    cp: 8,
    damage: 7,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/134.png",
    types: [waterType],
    created: new Date(),
  },
  {
    id: 19,
    name: "Voltali",
    hp: 26,
    cp: 8,
    damage: 7,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/135.png",
    types: [electrikType],
    created: new Date(),
  },
  {
    id: 20,
    name: "Pyroli",
    hp: 26,
    cp: 8,
    damage: 7,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/136.png",
    types: [fireType],
    created: new Date(),
  },
  {
    id: 21,
    name: "Mewtwo",
    hp: 30,
    cp: 15,
    damage: 10,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/150.png",
    types: [psyType],
    created: new Date(),
  },
  {
    id: 22,
    name: "Mew",
    hp: 30,
    cp: 12,
    damage: 9,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/151.png",
    types: [psyType],
    created: new Date(),
  },
  {
    id: 23,
    name: "Dracolosse",
    hp: 30,
    cp: 13,
    damage: 9,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/149.png",
    types: [FlyType],
    created: new Date(),
  },
  {
    id: 24,
    name: "Ronflex",
    hp: 30,
    cp: 10,
    damage: 8,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/143.png",
    types: [normalType],
    created: new Date(),
  },
  {
    id: 25,
    name: "Machopeur",
    hp: 28,
    cp: 8,
    damage: 7,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/067.png",
    types: [combatType],
    created: new Date(),
  },
  // 25 more popular Pokémon
  {
    id: 26,
    name: "Arcanin",
    hp: 30,
    cp: 10,
    damage: 8,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/059.png",
    types: [fireType],
    created: new Date(),
  },
  {
    id: 27,
    name: "Alakazam",
    hp: 28,
    cp: 12,
    damage: 9,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/065.png",
    types: [psyType],
    created: new Date(),
  },
  {
    id: 28,
    name: "Onix",
    hp: 30,
    cp: 7,
    damage: 6,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/095.png",
    types: [normalType],
    created: new Date(),
  },
  {
    id: 29,
    name: "Gyarados",
    hp: 30,
    cp: 13,
    damage: 9,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/130.png",
    types: [waterType, FlyType],
    created: new Date(),
  },
  {
    id: 30,
    name: "Lokhlass",
    hp: 30,
    cp: 12,
    damage: 8,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/131.png",
    types: [waterType],
    created: new Date(),
  },
  {
    id: 31,
    name: "Roucarnage",
    hp: 30,
    cp: 9,
    damage: 7,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/018.png",
    types: [normalType, FlyType],
    created: new Date(),
  },
  {
    id: 32,
    name: "Papilusion",
    hp: 28,
    cp: 8,
    damage: 7,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/012.png",
    types: [insectType, FlyType],
    created: new Date(),
  },
  {
    id: 33,
    name: "Rafflesia",
    hp: 30,
    cp: 8,
    damage: 7,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/045.png",
    types: [plantType, PoisonType],
    created: new Date(),
  },
  {
    id: 34,
    name: "Nidoqueen",
    hp: 30,
    cp: 10,
    damage: 8,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/031.png",
    types: [PoisonType],
    created: new Date(),
  },
  {
    id: 35,
    name: "Nidoking",
    hp: 30,
    cp: 11,
    damage: 8,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/034.png",
    types: [PoisonType],
    created: new Date(),
  },
  {
    id: 36,
    name: "Gengar",
    hp: 28,
    cp: 12,
    damage: 9,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/094.png",
    types: [PoisonType],
    created: new Date(),
  },
  {
    id: 37,
    name: "Rhinoféros",
    hp: 30,
    cp: 10,
    damage: 8,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/112.png",
    types: [normalType],
    created: new Date(),
  },
  {
    id: 38,
    name: "Magmar",
    hp: 30,
    cp: 10,
    damage: 8,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/126.png",
    types: [fireType],
    created: new Date(),
  },
  {
    id: 39,
    name: "Electrode",
    hp: 26,
    cp: 9,
    damage: 7,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/101.png",
    types: [electrikType],
    created: new Date(),
  },
  {
    id: 40,
    name: "Voltali",
    hp: 26,
    cp: 8,
    damage: 7,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/135.png",
    types: [electrikType],
    created: new Date(),
  },
  {
    id: 41,
    name: "Kabutops",
    hp: 30,
    cp: 9,
    damage: 7,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/141.png",
    types: [normalType],
    created: new Date(),
  },
  {
    id: 42,
    name: "Ptera",
    hp: 30,
    cp: 10,
    damage: 8,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/142.png",
    types: [FlyType],
    created: new Date(),
  },
  {
    id: 43,
    name: "Leviator",
    hp: 30,
    cp: 13,
    damage: 9,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/130.png",
    types: [waterType, FlyType],
    created: new Date(),
  },
  {
    id: 44,
    name: "Artikodin",
    hp: 30,
    cp: 14,
    damage: 10,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/144.png",
    types: [FlyType],
    created: new Date(),
  },
  {
    id: 45,
    name: "Electhor",
    hp: 30,
    cp: 14,
    damage: 10,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/145.png",
    types: [FlyType, electrikType],
    created: new Date(),
  },
  {
    id: 46,
    name: "Sulfura",
    hp: 30,
    cp: 14,
    damage: 10,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/146.png",
    types: [FlyType, fireType],
    created: new Date(),
  },
  {
    id: 47,
    name: "Minidraco",
    hp: 18,
    cp: 5,
    damage: 6,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/147.png",
    types: [normalType],
    created: new Date(),
  },
  {
    id: 48,
    name: "Hypnomade",
    hp: 28,
    cp: 10,
    damage: 8,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/097.png",
    types: [psyType],
    created: new Date(),
  },
  {
    id: 49,
    name: "Canarticho",
    hp: 22,
    cp: 7,
    damage: 6,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/083.png",
    types: [FlyType],
    created: new Date(),
  },
  {
    id: 50,
    name: "Dodrio",
    hp: 30,
    cp: 9,
    damage: 7,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/085.png",
    types: [normalType, FlyType],
    created: new Date(),
  },
    {
    id: 51,
    name: "Têtarte",
    hp: 22,
    cp: 6,
    damage: 6,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/061.png",
    types: [waterType],
    created: new Date(),
  },
  {
    id: 52,
    name: "Tartard",
    hp: 30,
    cp: 9,
    damage: 7,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/062.png",
    types: [waterType, combatType],
    created: new Date(),
  },
  {
    id: 53,
    name: "Abra",
    hp: 15,
    cp: 5,
    damage: 5,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/063.png",
    types: [psyType],
    created: new Date(),
  },
  {
    id: 54,
    name: "Kadabra",
    hp: 20,
    cp: 8,
    damage: 7,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/064.png",
    types: [psyType],
    created: new Date(),
  },
  {
    id: 55,
    name: "Machoc",
    hp: 20,
    cp: 7,
    damage: 6,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/066.png",
    types: [combatType],
    created: new Date(),
  },
  {
    id: 56,
    name: "Machamp",
    hp: 30,
    cp: 12,
    damage: 9,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/068.png",
    types: [combatType],
    created: new Date(),
  },
  {
    id: 57,
    name: "Chétiflor",
    hp: 16,
    cp: 4,
    damage: 5,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/069.png",
    types: [plantType, PoisonType],
    created: new Date(),
  },
  {
    id: 58,
    name: "Empiflor",
    hp: 28,
    cp: 9,
    damage: 7,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/071.png",
    types: [plantType, PoisonType],
    created: new Date(),
  },
  {
    id: 59,
    name: "Tentacool",
    hp: 18,
    cp: 5,
    damage: 5,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/072.png",
    types: [waterType, PoisonType],
    created: new Date(),
  },
  {
    id: 60,
    name: "Tentacruel",
    hp: 30,
    cp: 10,
    damage: 8,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/073.png",
    types: [waterType, PoisonType],
    created: new Date(),
  },
  {
    id: 61,
    name: "Racaillou",
    hp: 16,
    cp: 4,
    damage: 5,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/074.png",
    types: [normalType],
    created: new Date(),
  },
  {
    id: 62,
    name: "Gravalanch",
    hp: 24,
    cp: 7,
    damage: 6,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/075.png",
    types: [normalType],
    created: new Date(),
  },
  {
    id: 63,
    name: "Grolem",
    hp: 30,
    cp: 10,
    damage: 8,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/076.png",
    types: [normalType],
    created: new Date(),
  },
  {
    id: 64,
    name: "Ponyta",
    hp: 20,
    cp: 7,
    damage: 6,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/077.png",
    types: [fireType],
    created: new Date(),
  },
  {
    id: 65,
    name: "Galopa",
    hp: 28,
    cp: 10,
    damage: 8,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/078.png",
    types: [fireType],
    created: new Date(),
  },
  {
    id: 66,
    name: "Ramoloss",
    hp: 22,
    cp: 6,
    damage: 5,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/079.png",
    types: [waterType, psyType],
    created: new Date(),
  },
  {
    id: 67,
    name: "Flagadoss",
    hp: 30,
    cp: 9,
    damage: 7,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/080.png",
    types: [waterType, psyType],
    created: new Date(),
  },
  {
    id: 68,
    name: "Magnéti",
    hp: 14,
    cp: 5,
    damage: 5,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/081.png",
    types: [electrikType],
    created: new Date(),
  },
  {
    id: 69,
    name: "Magnéton",
    hp: 24,
    cp: 8,
    damage: 7,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/082.png",
    types: [electrikType],
    created: new Date(),
  },
  {
    id: 70,
    name: "Doduo",
    hp: 18,
    cp: 6,
    damage: 6,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/084.png",
    types: [normalType, FlyType],
    created: new Date(),
  },
  {
    id: 71,
    name: "Otaria",
    hp: 20,
    cp: 6,
    damage: 6,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/086.png",
    types: [waterType],
    created: new Date(),
  },
  {
    id: 72,
    name: "Lamantine",
    hp: 30,
    cp: 9,
    damage: 7,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/087.png",
    types: [waterType],
    created: new Date(),
  },
  {
    id: 73,
    name: "Tadmorv",
    hp: 18,
    cp: 5,
    damage: 5,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/088.png",
    types: [PoisonType],
    created: new Date(),
  },
  {
    id: 74,
    name: "Grotadmorv",
    hp: 28,
    cp: 8,
    damage: 7,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/089.png",
    types: [PoisonType],
    created: new Date(),
  },
  {
    id: 75,
    name: "Krabby",
    hp: 16,
    cp: 5,
    damage: 5,
    picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/098.png",
    types: [waterType],
    created: new Date(),
  }
];

export const POKEMON_RULES = {
  NAME_PATTERN: /^[a-zA-Zéè]+$/,
  MAX_NAME: 20,
  MIN_NAME: 3,
  MAX_LIFE: 30,
  HIGH_LIFE: 25,
  LOW_LIFE: 15,
  MIN_LIFE: 10,
  MAX_DAMAGE: 10,
  MIN_DAMAGE: 1,
  MIN_TYPES: 1,
  MAX_TYPES: 3,
} as const;
